version: '3.8'

services:
  app:
    build: .
    container_name: creatus-api
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=dev
      - HTTP_PORT=8080
      - DATABASE_URL=mongodb://mongodb:27017/creatus-database
      - JWT_SECRET=secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - creatus
    links:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - creatus

networks:
  creatus:
    driver: bridge

volumes:
  mongo-data:
