version: '3.8'

services:
  app:
    build: .
    container_name: creatus-api
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=dev
      - HTTP_PORT=8080
      - DATABASE_URL=mongodb+srv://jpsouzadasilva:C4r3PsiSWhvc0t7D@creatus-database.n2n9tor.mongodb.net/creatus-database?retryWrites=true&w=majority
      - JWT_SECRET=secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: